server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: Turabot
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true

  security:
    user:
      name: admin
      password: admin
